apiVersion: v2
appVersion: "25.0.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
  - condition: postgresql.enabled
    name: postgresql
    repository: https://deps.truecharts.org/
    version: 11.0.31
deprecated: false
description: Keycloak handles containerized environments such as Kubernetes or OpenShift as first-class citizens. This guide describes how to optimize and run the Keycloak container image to provide the best experience running a Keycloak container.
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/keycloak_icon_512px.svg
keywords:
  - keycloak
  - http
  - web
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: keycloak
sources:
  - https://www.keycloak.org/
type: application
version: 20.1
annotations:
  truecharts.org/catagories: |
    - cloud
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
